// <auto-generated />
using System;
using Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CanilAppDbContext))]
    [Migration("20260624004809_UsuarioStatusAuditoriaTokenVersion")]
    partial class UsuarioStatusAuditoriaTokenVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Backend.Models.CodigoAcesso.CodigoAcessoModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CodigoAcesso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "canil@acesso",
                            DataHoraAtualizacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditadoPor = "Sistema"
                        });
                });

            modelBuilder.Entity("Backend.Models.Estoque.ContadorLoteModel", b =>
                {
                    b.Property<string>("Tipo")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<long>("UltimoNumero")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Tipo");

                    b.ToTable("ContadoresLote");
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemComEstoqueBaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItensBase", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemEstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NFe")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "Lote");

                    b.HasIndex("Lote")
                        .IsUnique();

                    b.ToTable("ItensEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemNivelEstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelMinimoEstoque")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItensNivelEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.RetiradaEstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraRetirada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataValidadeLote")
                        .HasColumnType("TEXT");

                    b.Property<string>("De")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstavaVencido")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdUsuarioRecebedor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdUsuarioRetirante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeOuDescricaoSimples")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Para")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataHoraRetirada");

                    b.HasIndex("IdUsuarioRecebedor");

                    b.HasIndex("IdUsuarioRetirante");

                    b.ToTable("RetiradaEstoque");
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Backend.Models.Usuarios.UsuariosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Permissao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Backend.Models.Insumos.InsumosModel", b =>
                {
                    b.HasBaseType("Backend.Models.Estoque.ItemComEstoqueBaseModel");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoDetalhada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoSimplificada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Unidade")
                        .HasColumnType("INTEGER");

                    b.ToTable("Insumos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Medicamentos.MedicamentosModel", b =>
                {
                    b.HasBaseType("Backend.Models.Estoque.ItemComEstoqueBaseModel");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeComercial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicoAlvo")
                        .HasColumnType("INTEGER");

                    b.ToTable("Medicamentos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Produtos.ProdutosModel", b =>
                {
                    b.HasBaseType("Backend.Models.Estoque.ItemComEstoqueBaseModel");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoDetalhada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoSimples")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Unidade")
                        .HasColumnType("INTEGER");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", "ItemBase")
                        .WithMany("ItensEstoque")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemNivelEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", "ItemBase")
                        .WithOne("ItemNivelEstoque")
                        .HasForeignKey("Backend.Models.Estoque.ItemNivelEstoqueModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("Backend.Models.Estoque.RetiradaEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", null)
                        .WithMany()
                        .HasForeignKey("IdUsuarioRecebedor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", null)
                        .WithMany()
                        .HasForeignKey("IdUsuarioRetirante")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Insumos.InsumosModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Backend.Models.Insumos.InsumosModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Medicamentos.MedicamentosModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Backend.Models.Medicamentos.MedicamentosModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Produtos.ProdutosModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Backend.Models.Produtos.ProdutosModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemComEstoqueBaseModel", b =>
                {
                    b.Navigation("ItemNivelEstoque")
                        .IsRequired();

                    b.Navigation("ItensEstoque");
                });

            modelBuilder.Entity("Backend.Models.Usuarios.UsuariosModel", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
