// <auto-generated />
using System;
using Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CanilAppDbContext))]
    [Migration("20260705180720_TransferenciaResponsaveisDestinoOpcional")]
    partial class TransferenciaResponsaveisDestinoOpcional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Backend.Models.CodigoAcesso.CodigoAcessoModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CodigoAcesso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "canil@acesso",
                            DataHoraAtualizacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditadoPor = "Sistema"
                        });
                });

            modelBuilder.Entity("Backend.Models.Estoque.ContadorLoteModel", b =>
                {
                    b.Property<string>("Tipo")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<long>("UltimoNumero")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Tipo");

                    b.ToTable("ContadoresLote");
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemComEstoqueBaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItensBase", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemEstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUnidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NFe")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "IdUnidadeEstoque", "Lote");

                    b.HasIndex("IdUnidadeEstoque");

                    b.HasIndex("IdUnidadeEstoque", "Lote")
                        .IsUnique();

                    b.ToTable("ItensEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemNivelEstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUnidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelMinimoEstoque")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "IdUnidadeEstoque");

                    b.HasIndex("IdUnidadeEstoque");

                    b.ToTable("ItensNivelEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.MovimentacaoEstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraMovimentacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoadorDocumento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoadorNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("FornecedorDocumento")
                        .HasColumnType("TEXT");

                    b.Property<string>("FornecedorNome")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdItem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdRetirada")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdTransferencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUnidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NFe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrigemMovimentacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaldoAposMovimentacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoMovimentacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdRetirada");

                    b.HasIndex("IdTransferencia");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdItem", "Lote");

                    b.HasIndex("IdUnidadeEstoque", "DataHoraMovimentacao");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.RetiradaEstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraRetirada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataValidadeLote")
                        .HasColumnType("TEXT");

                    b.Property<string>("De")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstavaVencido")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdMovimentacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUnidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdUsuarioRecebedor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdUsuarioRetirante")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeOuDescricaoSimples")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Para")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataHoraRetirada");

                    b.HasIndex("IdUsuarioRecebedor");

                    b.HasIndex("IdUsuarioRetirante");

                    b.HasIndex("IdUnidadeEstoque", "DataHoraRetirada");

                    b.ToTable("RetiradaEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.TransferenciaEstoqueItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdItem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdMovimentacaoEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdMovimentacaoSaida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTransferencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdTransferencia");

                    b.ToTable("TransferenciasEstoqueItens");
                });

            modelBuilder.Entity("Backend.Models.Estoque.TransferenciaEstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataTransferencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUnidadeDestino")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUnidadeOrigem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdUsuarioAprovacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuarioEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdUsuarioRecebimento")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdUnidadeDestino");

                    b.HasIndex("IdUsuarioEnvio");

                    b.HasIndex("IdUsuarioRecebimento");

                    b.HasIndex("Status");

                    b.HasIndex("IdUnidadeOrigem", "IdUnidadeDestino", "DataTransferencia");

                    b.ToTable("TransferenciasEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.UnidadeEstoqueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("UnidadesEstoque");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataHoraAtualizacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataHoraCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditadorPor = "Sistema",
                            IsDeleted = false,
                            Nome = "Secretaria",
                            Sigla = "SEC",
                            Tipo = "ADMINISTRATIVO"
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataHoraAtualizacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataHoraCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditadorPor = "Sistema",
                            IsDeleted = false,
                            Nome = "Canil",
                            Sigla = "CAN",
                            Tipo = "OPERACIONAL"
                        });
                });

            modelBuilder.Entity("Backend.Models.Estoque.UsuarioUnidadeEstoqueModel", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUnidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeConsultar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeSaida")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeTransferirEnviar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeTransferirReceber")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUsuario", "IdUnidadeEstoque");

                    b.HasIndex("IdUnidadeEstoque");

                    b.ToTable("UsuariosUnidadesEstoque");
                });

            modelBuilder.Entity("Backend.Models.Permissoes.PermissaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhSistema")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EscopoUnidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("Backend.Models.Permissoes.UsuarioPermissaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPermissao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdUnidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdPermissao");

                    b.HasIndex("IdUnidadeEstoque");

                    b.HasIndex("IdUsuario", "IdPermissao", "IdUnidadeEstoque")
                        .IsUnique();

                    b.ToTable("UsuariosPermissoes");
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Backend.Models.UnidadeMedida.UnidadeMedidaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AplicavelInsumo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AplicavelMedicamento")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AplicavelProduto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("Backend.Models.Usuarios.UsuariosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditadorPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InactivatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Permissao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PodeGerenciarUnidadesMedida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Backend.Models.Insumos.InsumosModel", b =>
                {
                    b.HasBaseType("Backend.Models.Estoque.ItemComEstoqueBaseModel");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoDetalhada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoSimplificada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Unidade")
                        .HasColumnType("INTEGER");

                    b.ToTable("Insumos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Medicamentos.MedicamentosModel", b =>
                {
                    b.HasBaseType("Backend.Models.Estoque.ItemComEstoqueBaseModel");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeComercial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicoAlvo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unidade")
                        .HasColumnType("INTEGER");

                    b.ToTable("Medicamentos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Produtos.ProdutosModel", b =>
                {
                    b.HasBaseType("Backend.Models.Estoque.ItemComEstoqueBaseModel");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoDetalhada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoSimples")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Unidade")
                        .HasColumnType("INTEGER");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", "ItemBase")
                        .WithMany("ItensEstoque")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Estoque.UnidadeEstoqueModel", "UnidadeEstoque")
                        .WithMany()
                        .HasForeignKey("IdUnidadeEstoque")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemBase");

                    b.Navigation("UnidadeEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemNivelEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", "ItemBase")
                        .WithMany("ItensNivelEstoque")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Estoque.UnidadeEstoqueModel", "UnidadeEstoque")
                        .WithMany()
                        .HasForeignKey("IdUnidadeEstoque")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemBase");

                    b.Navigation("UnidadeEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.MovimentacaoEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Estoque.RetiradaEstoqueModel", "Retirada")
                        .WithMany()
                        .HasForeignKey("IdRetirada");

                    b.HasOne("Backend.Models.Estoque.TransferenciaEstoqueModel", "Transferencia")
                        .WithMany()
                        .HasForeignKey("IdTransferencia");

                    b.HasOne("Backend.Models.Estoque.UnidadeEstoqueModel", "UnidadeEstoque")
                        .WithMany()
                        .HasForeignKey("IdUnidadeEstoque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Retirada");

                    b.Navigation("Transferencia");

                    b.Navigation("UnidadeEstoque");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Models.Estoque.RetiradaEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", null)
                        .WithMany()
                        .HasForeignKey("IdUsuarioRecebedor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", null)
                        .WithMany()
                        .HasForeignKey("IdUsuarioRetirante")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.Estoque.TransferenciaEstoqueItemModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Estoque.TransferenciaEstoqueModel", "Transferencia")
                        .WithMany("Itens")
                        .HasForeignKey("IdTransferencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Transferencia");
                });

            modelBuilder.Entity("Backend.Models.Estoque.TransferenciaEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.UnidadeEstoqueModel", "UnidadeDestino")
                        .WithMany()
                        .HasForeignKey("IdUnidadeDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Estoque.UnidadeEstoqueModel", "UnidadeOrigem")
                        .WithMany()
                        .HasForeignKey("IdUnidadeOrigem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", "UsuarioEnvio")
                        .WithMany()
                        .HasForeignKey("IdUsuarioEnvio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", "UsuarioRecebimento")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRecebimento");

                    b.Navigation("UnidadeDestino");

                    b.Navigation("UnidadeOrigem");

                    b.Navigation("UsuarioEnvio");

                    b.Navigation("UsuarioRecebimento");
                });

            modelBuilder.Entity("Backend.Models.Estoque.UsuarioUnidadeEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.UnidadeEstoqueModel", "UnidadeEstoque")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdUnidadeEstoque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeEstoque");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Models.Permissoes.UsuarioPermissaoModel", b =>
                {
                    b.HasOne("Backend.Models.Permissoes.PermissaoModel", "Permissao")
                        .WithMany("Atribuicoes")
                        .HasForeignKey("IdPermissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Estoque.UnidadeEstoqueModel", "UnidadeEstoque")
                        .WithMany()
                        .HasForeignKey("IdUnidadeEstoque")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("UnidadeEstoque");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Insumos.InsumosModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Backend.Models.Insumos.InsumosModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Medicamentos.MedicamentosModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Backend.Models.Medicamentos.MedicamentosModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Produtos.ProdutosModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Backend.Models.Produtos.ProdutosModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemComEstoqueBaseModel", b =>
                {
                    b.Navigation("ItensEstoque");

                    b.Navigation("ItensNivelEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.TransferenciaEstoqueModel", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Backend.Models.Estoque.UnidadeEstoqueModel", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Backend.Models.Permissoes.PermissaoModel", b =>
                {
                    b.Navigation("Atribuicoes");
                });

            modelBuilder.Entity("Backend.Models.Usuarios.UsuariosModel", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
