// <auto-generated />
using System;
using Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CanilAppDbContext))]
    [Migration("20260423035925_atualizacaoTabelasParte2")]
    partial class atualizacaoTabelasParte2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Backend.Models.Estoque.ItemComEstoqueBaseModel", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdItem");

                    b.ToTable("ItensBase", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemEstoqueModel", b =>
                {
                    b.Property<int>("IdItem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lote")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NFe")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdItem", "Lote");

                    b.ToTable("ItensEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemNivelEstoqueModel", b =>
                {
                    b.Property<int>("IdItem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelMinimoEstoque")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdItem");

                    b.ToTable("ItensNivelEstoque");
                });

            modelBuilder.Entity("Backend.Models.Estoque.RetiradaEstoqueModel", b =>
                {
                    b.Property<int>("IdRetirada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2026, 4, 23, 3, 59, 25, 53, DateTimeKind.Utc).AddTicks(4206));

                    b.Property<DateTime>("DataHoraCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2026, 4, 23, 3, 59, 25, 53, DateTimeKind.Utc).AddTicks(3913));

                    b.Property<string>("De")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Para")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRetirada");

                    b.ToTable("RetiradaEstoque");
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Backend.Models.Usuarios.UsuariosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Permissao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Backend.Models.Insumos.InsumosModel", b =>
                {
                    b.HasBaseType("Backend.Models.Estoque.ItemComEstoqueBaseModel");

                    b.Property<string>("CodInsumo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoDetalhada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoSimplificada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Unidade")
                        .HasColumnType("INTEGER");

                    b.ToTable("Insumos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Medicamentos.MedicamentosModel", b =>
                {
                    b.HasBaseType("Backend.Models.Estoque.ItemComEstoqueBaseModel");

                    b.Property<string>("CodMedicamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoMedicamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeComercial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicoAlvo")
                        .HasColumnType("INTEGER");

                    b.ToTable("Medicamentos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Produtos.ProdutosModel", b =>
                {
                    b.HasBaseType("Backend.Models.Estoque.ItemComEstoqueBaseModel");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoDetalhada")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoSimples")
                        .HasColumnType("TEXT");

                    b.Property<string>("NFe")
                        .HasColumnType("TEXT");

                    b.Property<int>("Unidade")
                        .HasColumnType("INTEGER");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", "ItemBase")
                        .WithMany("ItensEstoque")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemNivelEstoqueModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", "ItemBase")
                        .WithOne("ItemNivelEstoque")
                        .HasForeignKey("Backend.Models.Estoque.ItemNivelEstoqueModel", "IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemBase");
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.HasOne("Backend.Models.Usuarios.UsuariosModel", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Insumos.InsumosModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Backend.Models.Insumos.InsumosModel", "IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Medicamentos.MedicamentosModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Backend.Models.Medicamentos.MedicamentosModel", "IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Produtos.ProdutosModel", b =>
                {
                    b.HasOne("Backend.Models.Estoque.ItemComEstoqueBaseModel", null)
                        .WithOne()
                        .HasForeignKey("Backend.Models.Produtos.ProdutosModel", "IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Estoque.ItemComEstoqueBaseModel", b =>
                {
                    b.Navigation("ItemNivelEstoque")
                        .IsRequired();

                    b.Navigation("ItensEstoque");
                });

            modelBuilder.Entity("Backend.Models.Usuarios.UsuariosModel", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
